spring:
  application:
    name: redis-performance
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/performance
    username: ancas19
    password: P0stgr3s#P4ssw0rd
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      timeout: 50000
