spring:
  application:
    name: redis-performance
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/performance
    username: postgres
    password: admin123
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      timeout: 50000
